### ISSUE TITLE
Bug before resizing

### ISSUE THREAD

**Issue by einenlum** [turboMaCk/Babylon-Grid#1]
I have a bug when I first arrive on a page (or reload) : 

![babylonbefore](https://cloud.githubusercontent.com/assets/5675200/3316122/9d4d8b08-f6ff-11e3-9d7b-0657030d8e89.png)

If I resize just a little bit, all is perfect : 

![babylonafter](https://cloud.githubusercontent.com/assets/5675200/3316133/ad153a5e-f6ff-11e3-8cee-66a880e69e34.png)

I tried to add "visibility: hidden" on the container, but it did not fix the bug.
Is it a known issue?

**Comment by Master-Antonio** [comment]
Can you post the solution please?
Because to me dont work.

**Comment by turboMaCk** [comment]
Hi Antonio,
can you please be more specific. I do not see what is the problem.

Basically what you have to do to make babylon grid work is to include it to project after jquery and initialize plugin on some element. What plugin does is that it setup structure of elements and set proper classes on dom nodes that **you have to style**. As you can [see in doc](https://github.com/turboMaCk/Babylon-Grid#setting-scheme)

This issue was related with forcing plugin to reset grid if something happens. It make no sense to calling this on `$(document).ready`. On document load you have to init grid with $('.element-class').babylongrid(). Remember that this will not work without styles.

**Comment by Master-Antonio** [comment]
I have the same problem of this topic.
Bug of size of card : https://i.gyazo.com/a21eb334cf27d483decc508b47a268a4.gif
Bug of resize browser windows : https://i.gyazo.com/66fd5ead4d2f5cd366da89c019b63d5f.gif

**Comment by turboMaCk** [comment]
Just trigger `bablongrind:resize` event on jequery element right after video/images are loaded. I'll post more details on this issue: https://github.com/turboMaCk/Babylon-Grid/issues/7

**Comment by Master-Antonio** [comment]
Ok.
